name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  # RUSTFLAGS: '-D warnings'

jobs:
  ci:
    name: Lint and tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Format
        run: make fmt

      - name: Clippy
        run: make clippy

      - name: Build
        run: make build

      - name: Tests
        run: make test
